// Skill groups mirror the technical skills section of the resume.
export const skillGroups = [
	{
		id: 1,
		icon: 'bx bx-code-alt',
		title: 'Languages',
		skills: ['Python', 'Java', 'C++', 'JavaScript', 'TypeScript', 'Go'],
	},
	{
		id: 2,
		icon: 'bx bx-brain',
		title: 'AI & Machine Learning',
		skills: [
			'PyTorch',
			'TensorFlow',
			'Keras',
			'Scikit-learn',
			'OpenCV',
			'Pandas',
			'NumPy',
			'Matplotlib',
			'Multimodal RAG',
		],
	},
	{
		id: 3,
		icon: 'bx bx-shield-quarter',
		title: 'Security & Threat Research',
		skills: [
			'Malware Analysis',
			'Reverse Engineering',
			'MITRE ATT&CK',
			'SIEM',
			'IDA Pro',
			'x64dbg',
			'OllyDbg',
			'DnSpy',
			'Wireshark',
		],
	},
	{
		id: 4,
		icon: 'bx bx-layer',
		title: 'Web & Backend',
		skills: [
			'React.js',
			'Angular',
			'Node.js',
			'Express.js',
			'Spring Boot',
			'Django',
			'Flask',
			'REST APIs',
		],
	},
	{
		id: 5,
		icon: 'bx bx-cloud',
		title: 'Cloud & DevOps',
		skills: [
			'AWS',
			'Google Cloud',
			'Docker',
			'Kubernetes',
			'Jenkins',
			'CI/CD',
			'Prometheus',
			'Git',
		],
	},
	{
		id: 6,
		icon: 'bx bx-data',
		title: 'Data & Databases',
		skills: [
			'MySQL',
			'PostgreSQL',
			'MongoDB',
			'DynamoDB',
			'Apache Spark',
			'Kafka',
		],
	},
];
